// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUZvAu4Rp0WQE4IRhz6DsJT7ErUCrRzH4',
    appId: '1:1047494261964:web:415452d31d2d42137e1669',
    messagingSenderId: '1047494261964',
    projectId: 'movie-bf9a5',
    authDomain: 'movie-bf9a5.firebaseapp.com',
    storageBucket: 'movie-bf9a5.firebasestorage.app',
    measurementId: 'G-LSBY5XZ0H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzsYa4VJqBeMmmvV0Ud6qBtU8Jo2Av23c',
    appId: '1:1047494261964:android:e757dd585e14c19b7e1669',
    messagingSenderId: '1047494261964',
    projectId: 'movie-bf9a5',
    storageBucket: 'movie-bf9a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbqcz7OB0RVbo_x5HZpHe3FumIlsSLTDE',
    appId: '1:1047494261964:ios:b2e7cfc5c42e16987e1669',
    messagingSenderId: '1047494261964',
    projectId: 'movie-bf9a5',
    storageBucket: 'movie-bf9a5.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbqcz7OB0RVbo_x5HZpHe3FumIlsSLTDE',
    appId: '1:1047494261964:ios:b2e7cfc5c42e16987e1669',
    messagingSenderId: '1047494261964',
    projectId: 'movie-bf9a5',
    storageBucket: 'movie-bf9a5.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUZvAu4Rp0WQE4IRhz6DsJT7ErUCrRzH4',
    appId: '1:1047494261964:web:693a9ca031ac598f7e1669',
    messagingSenderId: '1047494261964',
    projectId: 'movie-bf9a5',
    authDomain: 'movie-bf9a5.firebaseapp.com',
    storageBucket: 'movie-bf9a5.firebasestorage.app',
    measurementId: 'G-34TDGR27YV',
  );

}